config/authentication/urls.py
from django.urls import path
from .views import *


app_name = "authentication"

urlpatterns = [
    path("login/", login, name="login"),
    path("register/", register, name="register"),
    path("check-email/", check_email, name="check_email"),
    path("check-username/", check_username, name="check_username"),
    path("ajax_login/", ajax_login, name="ajax_login"),
    path("send_code/", send_code, name="send_code"),
    path("profile/", profile, name="profile"),
]

config/blog/urls.py
from django.urls import path
from .views import *

app_name = "blog"

urlpatterns = [
    path("blog-detail-<slug>",blog_detail,name="blog_detail")
]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("", include("main.urls")),
    path("", include("blog.urls")),
    path("auth/", include("authentication.urls")),
    path('social-auth/', include('social_django.urls', namespace='social')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path("", views.home, name="home"),
    path("contact-us", views.contact_us, name="contact_us"),
    path("faq", views.faq, name="faq"),
    path("about-us", views.about_us, name="about_us"),
]

config/authentication/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

# Create your models here.


from django.db import models
from django.contrib.auth.models import User
import uuid

class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="profile"
    )
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=11)
    address = models.CharField(max_length=255)
    image = models.ImageField(upload_to="user/profile/")
    slug = models.UUIDField(primary_key=True, default=uuid.uuid4)


    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

config/blog/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from ckeditor_uploader.fields import RichTextUploadingField
from django_jsonform.models.fields import ArrayField
from extensions.utils import jalali_converter

# Create your models here.


class Blog(models.Model):
    slug = models.UUIDField(primary_key=True, default=uuid.uuid4)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    banner = models.ImageField(upload_to="blogs/")
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=200)
    detail = RichTextUploadingField()
    date = models.DateField(auto_now_add=True)
    is_published = models.BooleanField(default=False)
    num_of_likes = models.IntegerField(default=0)
    tags = ArrayField(models.CharField(max_length=10, blank=True), size=8)

    def jpublish(self):
        return jalali_converter(self.date)

config/authentication/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from config.settings import EMAIL_HOST_USER
from random import randint

# Create your views here.


def login(request):

    return render(request, "authentication/login.html")


def register(request):
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        password = request.POST.get("password")
        user_object = User.objects.create(
            username=name, email=email, password=make_password(password)
        )
        user_object.save()
        auth.login(
            request, user_object, backend="django.contrib.auth.backends.ModelBackend"
        )
        return redirect("authentication:profile")

    return render(request, "authentication/register.html")


def check_email(request):
    email = request.GET.get("email", None)
    response = {"exists": User.objects.filter(email=email).exists()}
    return JsonResponse(response)


def check_username(request):
    username = request.GET.get("username", None)
    response = {"exists": User.objects.filter(username=username).exists()}
    return JsonResponse(response)


def ajax_login(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        user = auth.authenticate(request, email=email, password=password)
        if user is not None:
            auth.login(request, user)
            return JsonResponse({"success": True})
        else:
            return JsonResponse({"success": False, "error": "Invalid credentials"})
    return JsonResponse({"success": False, "error": "Only POST method is allowed"})


def send_code(request):
    email = request.GET.get("email", None)
    code = randint(1000,9999)
    html_content = render_to_string("email/authentication_code.html", {"code": code})
    text_content = strip_tags(html_content)
    email2 = EmailMultiAlternatives(
        "کد ورود",
        text_content,
        EMAIL_HOST_USER,
        [email],
    )
    email2.attach_alternative(html_content, "text/html")
    email2.send()
    return JsonResponse({"code": code})


@login_required
def profile(request):
    return render (request,"user/profile.html")

config/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.


def blog_detail(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    return render(request, "blog/blog-detail.html", {"blog": blog})

config/main/views.py
from django.shortcuts import render, redirect
from blog.models import Blog
from django.contrib import messages
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from config.settings import EMAIL_HOST_USER

# Create your views here.


def home(request):
    blog = Blog.objects.filter(is_published=True)[:3]
    context = {"blogs": blog}
    return render(request, "index.html", context)


def contact_us(request):
    if request.method == "POST":
        name = request.POST.get("name")
        user_email = request.POST.get("email")
        subject = request.POST.get("subject")
        message = request.POST.get("message")
        html_content = render_to_string(
            "email/contact_email.html",
            {"name": name, "email": user_email, "subject": subject, "message": message},
        )
        text_content = strip_tags(html_content)
        email = EmailMultiAlternatives(
            subject, text_content, EMAIL_HOST_USER, [EMAIL_HOST_USER]
        )
        email.attach_alternative(html_content, "text/html")
        email.send()
        html_content = render_to_string("email/contact_user_message.html")
        text_content = strip_tags(html_content)
        email2 = EmailMultiAlternatives(
            "پیام شما دریافت شد - از ارتباط شما سپاسگزاریم!",
            text_content,
            EMAIL_HOST_USER,
            [user_email],
        )
        email2.attach_alternative(html_content, "text/html")
        email2.send()
        return render(request, "email/mail-success.html")
    return render(request, "contact-us.html")


def faq(request):
    return render(request, "faq.html")


def about_us(request):
    return render(request, "about.html")

config/templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from theme-script.ir/templates/goemart/about.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 03 Oct 2024 15:25:54 GMT -->
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content>
    <meta name="keywords" content>

    <title>گومارت - الگوی HTML5 تجارت الکترونیک چند منظوره</title>

    <link rel="icon" type="image/x-icon" href="{% static "assets/img/logo/favicon.png" %}">

    <link rel="stylesheet" href="{% static "assets/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/all-fontawesome.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/animate.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/magnific-popup.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/jquery-ui.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/nice-select.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
</head>
<body>

<div class="preloader">
    <div class="loader-ripple">
        <div></div>
        <div></div>
    </div>
</div>


{% include "include/header.html" %}
<main class="main">

    <div class="site-breadcrumb">
        <div class="site-breadcrumb-bg" style="background: url({% static "assets/img/breadcrumb/01.jpg" %})"></div>
        <div class="container">
            <div class="site-breadcrumb-wrap">
                <h4 class="breadcrumb-title">درباره ما</h4>
                <ul class="breadcrumb-menu">
                    <li><a href="index-2.html"><i class="far fa-home"></i> صفحه اصلی</a></li>
                    <li class="active">درباره ما</li>
                </ul>
            </div>
        </div>
    </div>


    <div class="about-area py-100">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <div class="about-left wow fadeInLeft" data-wow-delay=".25s">
                        <div class="about-img">
                            <img src="{% static "assets/img/about/01.jpg" %}" alt>
                        </div>
                        <div class="about-experience">
                            <div class="about-experience-icon">
                                <img src="{% static "assets/img/icon/experience.svg" %}" alt>
                            </div>
                            <b>30 سال تجربه <br></b>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="about-right wow fadeInRight" data-wow-delay=".25s">
                        <div class="site-heading mb-3">
<span class="site-title-tagline justify-content-start">
<i class="flaticon-drive"></i> درباره ما
</span>
                            <h2 class="site-title">
                                بزرگترین <span>بازار خرید</span> آنلاین برای شما.
                            </h2>
                        </div>
                        <p>
                            لورم اپسیوم به سادگی متن ساختگی صنعت چاپ و حروفچینی است. لورم ایپسوم دارد
                            از زمانی که یک چاپگر ناشناس یک گالی را گرفت، متن ساختگی استاندارد صنعت بوده است
                            از نوع و آن را به هم زد تا یک کتاب نمونه تایپ بسازد. این نه تنها پنج جان سالم به در برده است
                            قرن ها، بلکه جهش به حروفچینی الکترونیکی، اساسا توسط تزریق باقی مانده است
                            طنز بدون تغییر
                        </p>
                        <p class="mt-10">
                            انواع مختلفی از معابر لورم اپسیوم در دسترس است، اما اکثریت آن را دارند
                            دچار تغییر به شکلی شده است، توسط شوخ طبعی تزریق شده، یا کلمات تصادفی که به نظر نمی رسند
                            حتی کمی قابل باور
                        </p>
                        <a href="{% url "main:contact_us" %}" class="theme-btn mt-4">بیشتر را کشف کنید<i
                                class="fas fa-arrow-left-long"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="counter-area pt-50 pb-50">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <div class="counter-box">
                        <div class="icon">
                            <img src="{% static "assets/img/icon/shopping.svg" %}" alt>
                        </div>
                        <div class="counter-info">
                            <div class="counter-amount">
                                <span class="counter" data-count="+" data-to="50" data-speed="3000">50</span>
                                <span class="counter-sign">هزار+</span>
                            </div>
                            <h6 class="title">فروش کل </h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="counter-box">
                        <div class="icon">
                            <img src="{% static "assets/img/icon/happy-customer.svg" %}" alt>
                        </div>
                        <div class="counter-info">
                            <div class="counter-amount">
                                <span class="counter" data-count="+" data-to="90" data-speed="3000">90</span>
                                <span class="counter-sign">هزار+</span>
                            </div>
                            <h6 class="title">مشتریان خوشحال</h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="counter-box">
                        <div class="icon">
                            <img src="{% static "assets/img/icon/employee.svg" %}" alt>
                        </div>
                        <div class="counter-info">
                            <div class="counter-amount">
                                <span class="counter" data-count="+" data-to="150" data-speed="3000">150</span>
                                <span class="counter-sign">هزار+</span>
                            </div>
                            <h6 class="title">کارگران تیم</h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="counter-box">
                        <div class="icon">
                            <img src="{% static "assets/img/icon/award.svg" %}" alt>
                        </div>
                        <div class="counter-info">
                            <div class="counter-amount">
                                <span class="counter" data-count="+" data-to="30" data-speed="3000">30</span>
                                <span class="counter-sign">هزار+</span>
                            </div>
                            <h6 class="title">برنده جایزه شوید</h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <div class="video-area pb-120">
        <div class="container-fluid px-0">
            <div class="video-content" style="background-image: url({% static "assets/img/video/01.jpg" %});">
                <div class="row align-items-center">
                    <div class="col-lg-12">
                        <div class="video-wrapper">
                            <a class="play-btn popup-youtube" href="https://www.youtube.com/watch?v=ckHzmP1evNU">
                                <i class="fas fa-play"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="feature-area bg-white pt-50 pb-50">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6 col-lg-3">
                    <div class="feature-item">
                        <div class="feature-icon">
                            <i class="fal fa-truck"></i>
                        </div>
                        <div class="feature-content">
                            <h4>تحویل رایگان</h4>
                            <p>سفارش‌های بیش از 120 ریال</p>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-3">
                    <div class="feature-item">
                        <div class="feature-icon">
                            <i class="fal fa-sync"></i>
                        </div>
                        <div class="feature-content">
                            <h4>بازپرداخت</h4>
                            <p>بازگرداندن ظرف 30 روز</p>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-3">
                    <div class="feature-item">
                        <div class="feature-icon">
                            <i class="fal fa-wallet"></i>
                        </div>
                        <div class="feature-content">
                            <h4>پرداخت مطمئن</h4>
                            <p>پرداخت 100% ایمن</p>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-3">
                    <div class="feature-item">
                        <div class="feature-icon">
                            <i class="fal fa-headset"></i>
                        </div>
                        <div class="feature-content">
                            <h4>پشتیبانی 24/7</h4>
                            <p>با ما تماس بگیرید</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="newsletter-area pt-60 pb-60">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mx-auto">
                    <div class="newsletter-content">
                        <h3>دریافت کوپن تخفیف <span>20%</span></h3>
                        <p>با مشترک شدن در خبرنامه ما</p>
                        <div class="subscribe-form">
                            <form action="#">
                                <input type="email" class="form-control" placeholder="آدرس ایمیل معتبر شما">
                                <button class="theme-btn" type="submit">
                                    اشتراک <i class="far fa-paper-plane"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="newsletter-img-1">
            <img src="{% static "assets/img/newsletter/01.png" %}" alt>
        </div>
        <div class="newsletter-img-2">
            <img src="{% static "assets/img/newsletter/02.png" %}" alt>
        </div>
    </div>

</main>

{% include "include/footer.html" %}


<a href="#" id="scroll-top"><i class="far fa-arrow-up-from-arc"></i></a>


<script data-cfasync="false" src="../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.html"></script>
<script src="{% static "assets/js/jquery-3.6.0.min.js" %}"></script>
<script src="{% static "assets/js/modernizr.min.js" %}"></script>
<script src="{% static "assets/js/bootstrap.bundle.min.js" %}"></script>
<script src="{% static "assets/js/imagesloaded.pkgd.min.js" %}"></script>
<script src="{% static "assets/js/jquery.magnific-popup.min.js" %}"></script>
<script src="{% static "assets/js/isotope.pkgd.min.js" %}"></script>
<script src="{% static "assets/js/jquery.appear.min.js" %}"></script>
<script src="{% static "assets/js/jquery.easing.min.js" %}"></script>
<script src="{% static "assets/js/owl.carousel.min.js" %}"></script>
<script src="{% static "assets/js/counter-up.js" %}"></script>
<script src="{% static "assets/js/jquery-ui.min.js" %}"></script>
<script src="{% static "assets/js/jquery.nice-select.min.js" %}"></script>
<script src="{% static "assets/js/countdown.min.js" %}"></script>
<script src="{% static "assets/js/wow.min.js" %}"></script>
<script src="{% static "assets/js/main.js" %}"></script>
</body>

<!-- Mirrored from theme-script.ir/templates/goemart/about.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 03 Oct 2024 15:25:57 GMT -->
</html>

config/templates/authentication/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from theme-script.ir/templates/goemart/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 03 Oct 2024 15:25:58 GMT -->
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content>
    <meta name="keywords" content>

    <title>گومارت - الگوی HTML5 تجارت الکترونیک چند منظوره</title>

    <link rel="icon" type="image/x-icon" href="{% static "assets/img/logo/favicon.png" %}">

    <link rel="stylesheet" href="{% static "assets/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/all-fontawesome.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/animate.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/magnific-popup.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/jquery-ui.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/nice-select.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
</head>
<body>

<div class="preloader">
    <div class="loader-ripple">
        <div></div>
        <div></div>
    </div>
</div>


{% include "include/header.html" %}

<main class="main">

    <div class="site-breadcrumb">
        <div class="site-breadcrumb-bg" style="background: url({% static "assets/img/breadcrumb/01.jpg" %})"></div>
        <div class="container">
            <div class="site-breadcrumb-wrap">
                <h4 class="breadcrumb-title">ورود به سیستم</h4>
                <ul class="breadcrumb-menu">
                    <li><a href="{% url "main:home" %}"><i class="far fa-home"></i> صفحه اصلی</a></li>
                    <li class="active">ورود به سیستم</li>
                </ul>
            </div>
        </div>
    </div>


    <div class="login-area py-100">
        <div class="container">
            <div class="col-md-7 col-lg-5 mx-auto">
                <div class="login-form">
                    <div class="login-header">
                        <img src="{% static "assets/img/logo/logo.png" %}" alt>
                        <p>با حساب گومارت خود وارد شوید</p>
                    </div>
                    <form method="post" id="login-form" action="{% url 'authentication:ajax_login' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>آدرس ایمیل</label>
                            <input required name="email" type="email" class="form-control" placeholder="ایمیل شما">
                        </div>
                        <div class="form-group">
                            <label>رمز عبور</label>
                            <input required name="password" type="password" class="form-control" placeholder="گذرواژه شما">
                        </div>
                        <div class="d-flex justify-content-between mb-4">
                            <div class="form-check">
                                <input required class="form-check-input" type="checkbox" value id="remember">
                                <label class="form-check-label" for="remember">
                                    مرا به خاطر بسپار
                                </label>
                            </div>
                            <a href="forgot-password.html" class="forgot-pass">گذرواژه را فراموش کرده‌اید؟</a>
                        </div>
                        <div class="d-flex align-items-center">
                            <button type="submit" class="theme-btn"><i class="far fa-sign-in"></i> ورود</button>
                        </div>
                    </form>
                    <div class="login-footer">
                        <p>حساب ندارید؟ <a href="{% url "authentication:register" %}">ثبت نام کنید.</a></p>
                        <div class="social-login">
                            <span class="social-divider">یا</span>
                            <p>ادامه با رسانه های اجتماعی</p>
                            <div class="social-login-list">
                                <a href="#" class="fb-auth"><i class="fab fa-facebook-f"></i> فیس بوک</a>
                                <a href="{% url 'social:begin' 'google-oauth2' %}" class="gl-auth"><i class="fab fa-google"></i> گوگل</a>
                                <a href="#" class="tw-auth"><i class="fab fa-twitter"></i> توییتر</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="newsletter-area pt-60 pb-60">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mx-auto">
                    <div class="newsletter-content">
                        <h3>دریافت کوپن تخفیف <span>20%</span></h3>
                        <p>با مشترک شدن در خبرنامه ما</p>
                        <div class="subscribe-form">
                            <form action="#">
                                <input type="email" class="form-control" placeholder="آدرس ایمیل معتبر شما">
                                <button class="theme-btn" type="submit">
                                    اشتراک <i class="far fa-paper-plane"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="newsletter-img-1">
            <img src="{% static "assets/img/newsletter/01.png" %}" alt>
        </div>
        <div class="newsletter-img-2">
            <img src="{% static "assets/img/newsletter/02.png" %}" alt>
        </div>
    </div>

</main>

{% include "include/footer.html" %}


<a href="#" id="scroll-top"><i class="far fa-arrow-up-from-arc"></i></a>


<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script data-cfasync="false" src="../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.html"></script>
<script src="{% static "assets/js/jquery-3.6.0.min.js" %}"></script>
<script src="{% static "assets/js/modernizr.min.js" %}"></script>
<script src="{% static "assets/js/bootstrap.bundle.min.js" %}"></script>
<script src="{% static "assets/js/imagesloaded.pkgd.min.js" %}"></script>
<script src="{% static "assets/js/jquery.magnific-popup.min.js" %}"></script>
<script src="{% static "assets/js/isotope.pkgd.min.js" %}"></script>
<script src="{% static "assets/js/jquery.appear.min.js" %}"></script>
<script src="{% static "assets/js/jquery.easing.min.js" %}"></script>
<script src="{% static "assets/js/owl.carousel.min.js" %}"></script>
<script src="{% static "assets/js/counter-up.js" %}"></script>
<script src="{% static "assets/js/jquery-ui.min.js" %}"></script>
<script src="{% static "assets/js/jquery.nice-select.min.js" %}"></script>
<script src="{% static "assets/js/countdown.min.js" %}"></script>
<script src="{% static "assets/js/wow.min.js" %}"></script>
<script src="{% static "assets/js/main.js" %}"></script>
<script src="{% static "assets/js/login.js" %}"></script>
</body>

<!-- Mirrored from theme-script.ir/templates/goemart/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 03 Oct 2024 15:25:58 GMT -->
</html>

config/templates/user/include/sidebar.html
{% load static %}
<div class="col-lg-3">
    <div class="sidebar">
        <div class="sidebar-top">
            <div class="sidebar-profile-img">
                <img src="{% static "assets/img/account/user.jpg" %}" alt>
                <button type="button" class="profile-img-btn"><i class="far fa-camera"></i></button>
                <input type="file" class="profile-img-file">
            </div>
            <h5>آنتونی جانسون</h5>
            <p><a href="https://theme-script.ir/cdn-cgi/l/email-protection" class="__cf_email__"
                  data-cfemail="0c6d62786362654c69746d617c6069226f6361">ad@info.com</a></p>
        </div>
        <ul class="sidebar-list">
            <li><a href="user-dashboard.html"><i class="far fa-gauge-high"></i> داشبورد</a></li>
            <li><a class="active" href="user-profile.html"><i class="far fa-user"></i> نمایه من</a>
            </li>
            <li><a href="order-list.html"><i class="far fa-shopping-bag"></i> فهرست سفارشات من <span
                    class="badge badge-danger">02</span></a></li>
            <li><a href="wishlist.html"><i class="far fa-heart"></i> فهرست علاقمندی های من <span
                    class="badge badge-danger">02</span></a></li>
            <li><a href="address-list.html"><i class="far fa-location-dot"></i> فهرست آدرس</a></li>
            <li><a href="support-ticket.html"><i class="far fa-headset"></i> بلیط‌های پشتیبانی <span
                    class="badge badge-danger">02</span></a></li>
            <li><a href="track-order.html"><i class="far fa-map-location-dot"></i> سفارش من را پیگیری کنید</a>
            </li>
            <li><a href="payment-method.html"><i class="far fa-wallet"></i> روش‌های پرداخت</a></li>
            <li><a href="user-notification.html"><i class="far fa-bell"></i> اعلان <span
                    class="badge badge-danger">02</span></a></li>
            <li><a href="user-message.html"><i class="far fa-envelope"></i> پیام‌ها <span
                    class="badge badge-danger">02</span></a></li>
            <li><a href="user-setting.html"><i class="far fa-gear"></i> تنظیمات</a></li>
            <li><a href="#"><i class="far fa-sign-out"></i> خروج</a></li>
        </ul>
    </div>
</div>